---
features:
  - |
    Adds support for creating, reading, and deleting application credentials
    via the ``appication credential`` command. With application credentials, a
    user can grant their applications limited access to their cloud resources.
    Once created, users can authenticate with an application credential by
    using the ``v3applicationcredential`` auth type.
    [`blueprint application-credentials <https://blueprints.launchpad.net/keystone/+spec/application-credentials>`_]
